SEGA Saturn / Super-H architecture
Kingcom/armips pull request #230
Opened 2022-10-06 22:25 UTC by Fothsid

Mainly adds the SEGA Saturn / Super-H 2 architecture & instruction set support. (`.saturn` directive)
The code was based on the MIPS parser.

Minor changes include:
- Added a fallback to the ELF relocator for PSX architecture, in case if the PSX relocator doesn't succeed.
- Changed ELF file handling code to support RELA sections (REL, but with an addend)

2022-10-10 16:11 UTC, Fothsid commented
I see the compilation issues with MSVC, will try to patch them up soon.

2022-10-10 16:35 UTC, sp1187 commented
Some additional test cases, preferably at least one of every single opcode would be nice to ensure its encoding is correct (no typo regressions later etc.).

2022-10-12 17:14 UTC, Fothsid commented
Made a test for every SH1/SH2 opcode, turned out there were some bugs, which I fixed. Expected output was taken from GCC's SH assembler.

2022-10-13 15:58 UTC, Kingcom requested changes

2022-10-13 15:58 UTC, Kingcom commented on Commands/CDirectiveFile.cpp
> +		success = true;
`success` is already true at this point.

2022-10-13 17:42 UTC, Fothsid commented on Archs/SuperH/CShInstruction.cpp
> +int getImmediateBits(ShImmediateType type)
Done.

2022-10-13 17:44 UTC, Fothsid commented on Archs/SuperH/CShInstruction.cpp
> +		Logger::queueError(Logger::Error, "opcode not aligned to word boundary");
Yes. On Super-H, a word is a 16-bit value. Instructions like `mov.w` store/load 16-bit values, whereas `mov.l` does 32-bit values.

2022-10-13 17:46 UTC, Fothsid commented on Archs/SuperH/ShOpcodes.cpp
> +		I think I'll have all immediate byte values require a hash before it, just for
Added aliases for the instructions with the immediate 8-bit values.

2022-10-16 13:49 UTC, sp1187 commented
Another thing I thought of: Since the Sega 32X uses the same SH2 CPU, do you think it would make sense to add a `.32x` alias directive that maps to the same action as `.saturn`?

2022-10-16 14:18 UTC, Fothsid commented
That does sound interesting. I completely forgot that 32x is a thing, haha. I'll probably add it in a bit.

2022-10-17 17:35 UTC, Kingcom commented
Is there any odd memory mapping on the 32X, like on SNES? If there isn't full support for the system or it needs workarounds, it should be mentioned in the Readme. Can you also add the directive to it?

2022-10-17 18:08 UTC, merged